### ISSUE TITLE
I couldn't follow the guide after Step 16?

### ISSUE THREAD

**Issue by socksprox** [Lazr1026/regionchange#3]
There are only 3 options, but those are for wii u menu. 

My wii u is japanese region and I wanna change it to european. Changing the coldboot title from wii u menu (jpn) to (eur) didn't work,error: Error! Make sure title is installed correctly

after booting, i only see some bubbles...
![signal-2024-02-17-193603](https://github.com/Lazr1026/regionchange/assets/36358673/89e9abab-fb63-47ff-87da-9e8dcd8d6f26)
![signal-2024-02-17-193846](https://github.com/Lazr1026/regionchange/assets/36358673/beab0167-57b1-4af1-9da3-809d287a4216)

**Comment by Lazr1026** [comment]
use my recovery_menu
